### ISSUE TITLE
Implement left-to-right order of evaluation?

### ISSUE THREAD

**Issue by arjunguha** [mgree/mgt#15]
I am trying to use the type migration algorithm in the repository to port my untyped code to OCaml, because that's what everyone should do!

My untyped code is written in Racket (or JavaScript or Python), which has a left-to-right order of evaluation. However, the generated code seems to inherit OCaml's order of evaluation, which is to evaluate the argument before the function.

Here is an example that shows that this difference is observable:

The following program raises an exception `0` because the condition is not a boolean:

```
$ cat arg.mgt
if ((\x:? . x) 200) then 1 else 0
$ ./target/debug/mgt -a dynamic -m compile -o ex arg.mgt && ./ex/arg_dynamic.exe

PROGRAM dynamic
if [bool?] (\x : ?. x) ([int!] 200) then 1 else 0
:
int
Fatal error: exception Mgt.Runtime.Coercion_failure(0, _)
```

The following programming raises exception `4` because the expression in function position is not a function:

```
$ cat fun.mgt
((\y:? . y) 400) 0
arjun@arjun-linux-vm:~/repos/github/mgree/mgt$ ./target/debug/mgt -a dynamic -m compile -o ex fun.mgt && ./ex/fun_dynamic.exe

PROGRAM dynamic
([fun?] (\y : ?. y) ([int!] 400)) ([int!] 0)
:
?
Fatal error: exception Mgt.Runtime.Coercion_failure(4, _)
```

Now, let's put those two programs together:

```
$ cat app.mgt
((\y:? . y) 400) (if ((\x:? . x) 200) then 1 else 0)
```

If this were left-to-right evaluation, I would expect exception `4`. However, what I get is exception `0`:

```
t$ ./target/debug/mgt -a dynamic -m compile -o ex app.mgt && ./ex/app_dynamic.exe

PROGRAM dynamic
([fun?] (\y : ?. y) ([int!] 400))
([int!] if [bool?] (\x : ?. x) ([int!] 200) then 1 else 0)
:
?
Fatal error: exception Mgt.Runtime.Coercion_failure(0, _)
```

Could add a feature flag to get left-to-right evaluation?

**Comment by mgree** [comment]
Thank you for this valuable report! I am very excited that you are converting your programs to types. It seems like it'd be sufficient to let-lift the function position of an application, i.e., translating:

```
e1 e2 e3 ... en
```

into 

```
let f_fresh = e1 in
f_fresh e2 e3 ... en
```

Assuming that `f_fresh` is, indeed, fresh. Does that seem right to you? I can put this behavior behind a flag, but I might as well make it the default.

Now, I'd of course like to remind you that for your Scheme programs to be portable, they can't make assumptions about order of evaluation in general application forms.

**Comment by arjunguha** [comment]
So, you want me to manually convert my programs to A Normal Form? That seems like a lot of work. I am bad at picking fresh variable names. But, it seems odd that this restructuring is needed at all. How about adding a "reverse app" combinator to the runtime system:

```
let rev_app x f = f x
```

So, your compiler could insert calls to `rev_app`, which would preserve the program structure.

**Comment by mgree** [comment]
I was going to do it for you! But... who doesn't love a good hack? 😁 I like `rev_app`.

**Comment by mgree** [comment]
Hmm... unfortunately, [OCaml also leaves evaluation order unspecified](http://caml.inria.fr/pub/docs/manual-ocaml/expr.html#sss:expr-functions-application), so `rev_app` won't always be a safe bet.

I'm afraid ANF may truly be necessary, unfortunately.

**Comment by mgree** [comment]
Fixed in 33e6a90.

**Comment by mgree** [comment]
And can be turned off by a `--skip-ltr` flag in 5151495. Pleasure doing business with you; please avoid using variable names that start with `__mgt`.

**Comment by arjunguha** [comment]
How awful. I c

> Hmm... unfortunately, [OCaml also leaves evaluation order unspecified](http://caml.inria.fr/pub/docs/manual-ocaml/expr.html#sss:expr-functions-application), so `rev_app` won't always be a safe bet.
> 
> I'm afraid ANF may truly be necessary, unfortunately.

Ah, I see the argument for Standard ML now.
